# Generated by Django 5.2.7 on 2025-11-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
