# Generated by Django 5.2.7 on 2025-12-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancel_message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='canceled_at',
        ),
    ]
