# Generated by Django 5.2.7 on 2025-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_serviceprovider_first_name_serviceprovider_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='providerName',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='appointmentName',
            field=models.CharField(default='Appointment', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='qualifications',
            field=models.TextField(default='Qualifications', max_length=200),
        ),
    ]
