# Generated by Django 5.2.7 on 2025-12-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_booking_cancel_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentslot',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='appointmentslot',
            old_name='is_booked',
            new_name='isBooked',
        ),
        migrations.RenameField(
            model_name='appointmentslot',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='bookedAt',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='canceled_msgs',
            new_name='canceledMsgs',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='canceled_msgs',
            new_name='canceledMsgs',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
