# Generated by Django 5.2.7 on 2025-10-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointmentslot_providerusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='appointmentType',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='providerFirstName',
            field=models.CharField(default='FirstName', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='providerLastName',
            field=models.CharField(default='LastName', max_length=50),
        ),
    ]
