# Generated by Django 5.2.7 on 2025-10-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_adminprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='first_name',
            field=models.CharField(default='Provider', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='last_name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
