# Generated by Django 5.2.7 on 2025-10-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_appointmentslot_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='providerUsername',
            field=models.CharField(default='provider', max_length=150),
        ),
    ]
