# Generated by Django 5.2.7 on 2025-10-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointmentslot_providerusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='providerFirstName',
            field=models.CharField(default='Provider', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='providerLastname',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
