# Generated by Django 5.2.7 on 2025-10-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_appointmentslot_providerfirstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentslot',
            old_name='providerLastname',
            new_name='providerLastName',
        ),
    ]
