# Generated by Django 5.2.7 on 2025-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_providerlastname_appointmentslot_providerlastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='appointmentType',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
